### ISSUE TITLE
ENH: move auth azure out of module

### ISSUE THREAD

**Issue by erfannariman** [zypp-io/df_to_azure#60]
Nu wordt de database connectie gemaakt in de module, daarmee moeten de users nog meer environment variabele definiëren voor de module. Ik denk dat het beter zou zijn als we `connectie` als argument accepteren in onze functies die met de database te maken hebben en dat stuk dus buiten deze module laten.

@melvinfolkers wat denk jij?

**Comment by melvinfolkers** [comment]
Hmmm.

De database credentials worden niet alleen gebruikt voor de connection string, maar ook voor het aanmaken van de linked service in azure data factory. Je hebt dus echt de uid, Pw, server en db naam nodig om het stuk in ADF werkend te krijgen.

Dus de enige oplossing zou zijn om dan 4 extra argumenten op te geven in de functie, en dat lijkt me niet handig.

Anders maandag ff bespreken?

**Comment by erfannariman** [comment]
Mee eens dat deze in de repo hoort.
