### ISSUE TITLE
BUG: error for wrong method

### ISSUE THREAD

**Issue by melvinfolkers** [zypp-io/df_to_azure#72]
We have to add an exception in case a method is used that is not supported by this package:

for instance this method does not exist

```python
method="insert"
```

instead of throwing an error, it appends the dataset to the sql database.

**Comment by erfannariman** [comment]
Fixed in: https://github.com/zypp-io/df_to_azure/blob/75bad0a4d554b8b0060baee65b4a1c56c3bddbd7/df_to_azure/parse_settings.py#L25-L31
